#  Tensor

In [1]:
from __future__ import print_function
import torch

In [8]:
torch.rand(5, 3)  # 0-1分布

tensor([[0.3838, 0.9067, 0.4630],
        [0.7232, 0.5060, 0.8794],
        [0.0599, 0.6292, 0.9614],
        [0.4129, 0.3208, 0.3685],
        [0.7015, 0.9147, 0.1028]])

In [14]:
torch.randn((5, 3), dtype=torch.float32)  # 标准正态分布

tensor([[-0.1489, -2.4803,  0.6956],
        [-0.8994, -0.1503,  1.1280],
        [ 0.3951, -2.4111, -1.1678],
        [-0.9705, -1.3674, -1.1663],
        [ 1.2125,  1.3097, -1.0627]])

In [16]:
torch.tensor([[1,2,3], [4,5,6]], dtype=torch.float32)  # 直接初始化

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [18]:
x = torch.ones((2,3))
x.size()  # size函数返回一个元组

torch.Size([2, 3])

#  Operation

In [21]:
# 以加法为例，可以用torch.add函数，也可以直接用 + ，结果可以直接放在等号左边，也可以用out参数指定。
# 也可以用原地操作，原地操作一般以下划线结尾，例如 y.add_(x)
x = torch.randn(2, 3)
y = torch.randn(2, 3)
z = torch.empty(2, 3)
r = torch.add(x, y, out=z)
print(z)
print(r)

tensor([[ 1.6612,  0.6502,  0.6027],
        [-0.0241,  0.9106, -1.1017]])
tensor([[ 1.6612,  0.6502,  0.6027],
        [-0.0241,  0.9106, -1.1017]])


In [35]:
print("原始的x\n", x)
x2 = x[:, 1]
print("x的第一列\n", x2)
x2.add_(torch.tensor([1.2, 2.3]))
print("x的第一列，原地增加后\n", x2)
print("切片改变后的x\n",x)
# tensor 切片操作是引用，原始的数据会受到改变

原始的x
 tensor([[ 1.2468, 11.5962, -0.3295],
        [-1.1261, 21.3879, -1.0395]])
x的第一列
 tensor([11.5962, 21.3879])
x的第一列，原地增加后
 tensor([12.7962, 23.6879])
切片改变后的x
 tensor([[ 1.2468, 12.7962, -0.3295],
        [-1.1261, 23.6879, -1.0395]])


In [42]:
x = torch.randn((3, 4))
y = x.view((2, 6))
print(x)
print(y)
print(x.reshape(2,6))

tensor([[ 0.8708, -0.2877, -0.4856,  0.4297],
        [ 0.0462, -0.1027,  0.8725,  1.4353],
        [ 0.7700, -0.0044, -0.1507,  0.9506]])
tensor([[ 0.8708, -0.2877, -0.4856,  0.4297,  0.0462, -0.1027],
        [ 0.8725,  1.4353,  0.7700, -0.0044, -0.1507,  0.9506]])
tensor([[ 0.8708, -0.2877, -0.4856,  0.4297,  0.0462, -0.1027],
        [ 0.8725,  1.4353,  0.7700, -0.0044, -0.1507,  0.9506]])


In [44]:
x = torch.rand(1)
print(x)
print(x.item())

tensor([0.0984])
0.09837383031845093


# Numpy Bridge

In [45]:
x = torch.randn(2,5)
print(x)
print(x.numpy())

tensor([[-0.2467,  0.0880, -0.1445, -0.6406, -0.5859],
        [ 1.7222,  0.6714, -2.0902,  0.0662,  0.9268]])
[[-0.24667381  0.08802854 -0.14449818 -0.64063996 -0.58589536]
 [ 1.7221843   0.67141485 -2.0901568   0.06619217  0.9268441 ]]


In [47]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
b.add_(1)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# Cuda Tensor

In [48]:
x = torch.randn((2, 3))
y = torch.ones_like(x)

if torch.cuda.is_available():
    device = torch.device("cuda")
    x = x.to("cuda")
    y = y.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", dtype=torch.float))
else:
    print("No cuda")